// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: requestvote.proto

package raft.rpcmodule.requestvote;

public interface RequestVoteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.RequestVoteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
